//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TalkMasterConsole.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TALKMASTERCONSOLE_DIALOG    102
#define IDS_STRING102                   102
#define IDS_STRING_ULAW_NOT_AVAIL       102
#define IDR_HTML_DAPREFERENCESDLG       103
#define IDS_STRING103                   103
#define IDS_STRING_MIC_CODEC_NOT_AVAIL  103
#define IDS_STRING104                   104
#define IDS_STRING105                   105
#define IDS_STRING106                   106
#define IDS_STRING107                   107
#define IDS_STRING_SERVER_GROUP_EMPTY_OR_UNAVAILABLE 107
#define IDS_STRING108                   108
#define IDS_STRING_INFORMATION          108
#define IDS_STRING109                   109
#define IDS_STRING110                   110
#define IDS_STRING_ERROR                110
#define IDS_STRING111                   111
#define IDS_STRING112                   112
#define IDS_STRING113                   113
#define IDS_STRING114                   114
#define IDS_STRING115                   115
#define IDS_STRING116                   116
#define IDS_STRING117                   117
#define IDS_STRING118                   118
#define IDS_STRING_SELECT_ICOM          118
#define IDS_STRING119                   119
#define IDS_STRING120                   120
#define IDS_STRING121                   121
#define IDS_STRING122                   122
#define IDS_STRING123                   123
#define IDS_STRING_STATUS_TALKING_TO    123
#define IDS_STRING124                   124
#define IDS_STRING_STATUS_DISCONNECTED  124
#define IDS_STRING125                   125
#define IDS_STRING_STATUS_CONNECTED     125
#define IDS_STRING126                   126
#define IDS_STRING_STATUS_TALKING       126
#define IDS_STRING127                   127
#define IDS_STRING_STATUS_LISTENING     127
#define IDS_STRING128                   128
#define IDS_STRING_STATUS_COMMAND       128
#define IDR_MENU_MAIN                   129
#define IDS_STRING129                   129
#define IDS_STRING_STATUS_IN_USE        129
#define IDB_BITMAP_LISTEN_OFF           130
#define IDS_STRING130                   130
#define IDS_STRING_STATUS_UNKNOWN       130
#define IDB_BITMAP_TALK_OFF             131
#define IDS_STRING131                   131
#define IDB_BITMAP_LISTEN_ON            132
#define IDD_DIALOG_PREFERENCES          132
#define IDS_STRING132                   132
#define IDB_BITMAP_TALK_ON              133
#define IDS_STRING133                   133
#define IDD_DIALOG_UNATTENDED           134
#define IDS_STRING134                   134
#define IDS_STRING135                   135
#define IDS_STRING136                   136
#define IDR_MAINFRAME                   137
#define IDS_STRING137                   137
#define IDR_MAINFRAME1                  138
#define IDB_BITMAP_PLAY                 138
#define IDS_STRING138                   138
#define IDR_MAINFRAME2                  139
#define IDB_BITMAP_PAUSE                139
#define IDD_DIALOG_LOGON                139
#define IDS_STRING139                   139
#define IDB_BITMAP_STOP                 140
#define IDS_STRING140                   140
#define IDS_STRING_LOGIN_RETRY          140
#define IDB_BITMAP_MUTE_OFF             141
#define IDS_STRING141                   141
#define IDS_STRING_LOGIN_REQUIRED       141
#define IDB_BITMAP_MUTE_ON              142
#define IDS_STRING142                   142
#define IDB_BITMAP_DOOR_CLOSED          143
#define IDS_STRING143                   143
#define IDB_BITMAP1                     144
#define IDB_BITMAP_DOOR_OPEN            144
#define IDS_STRING144                   144
#define IDB_BITMAP_CQ_OVERFLOW          145
#define IDS_STRING145                   145
#define IDB_BITMAP_CQ_PRIORITY          146
#define IDS_STRING146                   146
#define IDB_BITMAP_CQ_LOCAL             147
#define IDS_STRING147                   147
#define IDB_BITMAP_CQ_HOLD              148
#define IDS_STRING148                   148
#define IDB_BITMAP_CQ_NORMAL            149
#define IDS_STRING149                   149
#define IDS_STRING_WAV_FILE_FILTER      149
#define IDD_DIALOG_ANNOUNCE             150
#define IDS_STRING150                   150
#define IDS_STRING_WAV                  150
#define IDI_ICON1                       151
#define IDI_ICON_TASK_BAR               151
#define IDS_STRING151                   151
#define IDS_STRING_ULAW                 151
#define IDB_BITMAP2                     152
#define IDB_BITMAP_LOGO                 152
#define IDS_STRING152                   152
#define IDS_STRING_PCM                  152
#define IDB_BITMAP_VU_RED               153
#define IDS_STRING153                   153
#define IDB_BITMAP_VU_YELLOW            154
#define IDS_STRING154                   154
#define IDB_BITMAP_VU_GREEN             155
#define IDS_STRING155                   155
#define IDB_BITMAP3                     156
#define IDB_BITMAP_VU_BLANK             156
#define IDS_STRING156                   156
#define IDB_BITMAP_TALK_DISABLE         157
#define IDS_STRING157                   157
#define IDB_BITMAP5                     158
#define IDB_BITMAP_LISTEN_DISABLE       158
#define IDS_STRING158                   158
#define IDB_BITMAP_LOGO1                159
#define IDS_STRING159                   159
#define IDR_MENU_RCLICCK                160
#define IDS_STRING160                   160
#define IDI_ICON2                       161
#define IDR_MAINFRAME_NEW               161
#define IDS_STRING161                   161
#define IDI_ICON3                       162
#define IDI_ICON_PRIMEX                 162
#define IDS_STRING162                   162
#define IDS_STRING_COL_GRP              162
#define IDS_STRING163                   163
#define IDS_STRING_COL_LOCATION         163
#define IDB_BITMAP_DOOR_LOCKED_CLOSED   164
#define IDS_STRING164                   164
#define IDS_STRING_COL_QUEUE            164
#define IDS_STRING165                   165
#define IDS_STRING_COL_STATUS           165
#define IDB_BITMAP_DOOR_UNLOCKED_CLOSED 166
#define IDS_STRING166                   166
#define IDS_STRING_COL_DOOR_GATE        166
#define IDS_STRING167                   167
#define IDS_STRING_COL_IP_ADDRESS       167
#define IDB_BITMAP_DOOR_LOCKED_OPEN     168
#define IDS_STRING168                   168
#define IDB_BITMAP6                     169
#define IDB_BITMAP_DOOR_UNLOCKED_OPEN   169
#define IDS_STRING169                   169
#define IDB_BITMAP_FDX_MUTE             170
#define IDS_STRING170                   170
#define IDB_BITMAP_FDX_MUTED            171
#define IDS_STRING171                   171
#define IDB_BITMAP_FDX_MUTE_DISABLED    172
#define IDS_STRING172                   172
#define IDB_BITMAP_FDX_TALK_DISABLED    173
#define IDS_STRING173                   173
#define IDS_STRING_OPERATOR_CONSOLE     173
#define IDB_BITMAP_FDX_TALK_OFF         174
#define IDS_STRING174                   174
#define IDB_BITMAP_FDX_TALK_ON          175
#define IDS_STRING175                   175
#define IDS_STRING_STOP_FILE            175
#define IDB_BITMAP_NO_LISTEN_OFF        176
#define IDS_STRING176                   176
#define IDS_STRING_PLAY_FILE            176
#define IDB_BITMAP7                     177
#define IDB_BITMAP_NO_LISTEN_ON         177
#define IDS_STRING177                   177
#define IDS_STRING_CURRENTLY_PLAYING_AUDIO 177
#define IDS_STRING178                   178
#define IDS_STRING179                   179
#define IDB_BITMAP_DOOR_NONE            179
#define IDS_STRING180                   180
#define IDS_STRING_PREFERENCES          180
#define IDD_DIALOG_SEND_MESSAGE         180
#define IDS_STRING181                   181
#define IDD_DIALOG1                     181
#define IDD_DIALOG_PLEASE_WAIT          181
#define IDS_STRING182                   182
#define IDB_BITMAP_PRIORITY_LOW         182
#define IDS_STRING183                   183
#define IDB_BITMAP_PRIORITY_MEDIUM      183
#define IDS_STRING184                   184
#define IDB_BITMAP_PRIORITY_HIGH        184
#define IDS_STRING185                   185
#define IDR_MENU1                       185
#define IDR_MENU_GROUP_RCLICK           185
#define IDS_STRING_MUST_SELECT_ICOMS    186
#define IDB_BITMAP_GROUP_FULL           186
#define IDS_STRING_NO_ICOM_SELECTED     187
#define IDB_BITMAP_GROUP_PARTIAL        187
#define IDS_STRING_TEST_AUDIO           188
#define IDB_BITMAP_GROUP_EMPTY          188
#define IDS_STRING_WAITING_FOR_LOGIN_RETRY 189
#define IDB_BITMAP_SESSION_START        189
#define IDS_STRING_GROUP_NAME           190
#define IDB_BITMAP_SESSION_STOP         190
#define IDS_STRING_GLOBAL_GROUP         191
#define IDD_DIALOG_TEST_LOGON           191
#define IDS_STRING_COL_MSG_PRIORITY     192
#define IDS_STRING_COL_MSG_TITLE        193
#define IDS_STRING_NO_MESSAGES_SELECTED 194
#define IDS_STRING_SELECT_MESSAGE       195
#define IDS_STRING_SERVER_FILE_NOT_FOUND 196
#define IDS_STRING_STATUS_FDX           197
#define IDS_STRING_GROUP_NO_GROUP_SELECTED 198
#define IDS_STRING_GROUP_NO_INTERCOMS_IN_GROUP 199
#define IDS_STRING_GROUP_NO_COMMON_MESSAGES_FOUND 200
#define IDS_STRING_LOGON_OPTIONS_LESS   201
#define IDS_STRING_LOGON_OPTIONS_MORE   202
#define IDS_STRING_NO_MESSAGES_WAITING  203
#define IDS_STRING_INTERCOM_ALREADY_IN_USE 204
#define IDS_STRING_INTERCOMS            205
#define IDS_STRING_GROUPS               206
#define IDS_STRING_NAME_NOT_SET         207
#define IDS_STRING_INTERCOM_NAME_S      208
#define IDS_STRING_INTERCOM_ID_02X_02X_02X 209
#define IDS_STRING_NIC_VERSION_D_D_D    210
#define IDS_STRING_OS_VERSION_D_D_D_D_D 211
#define IDS_STRING_OS_VERSION_D_D_D_D_C 212
#define IDS_STRING_NIC_OPTIONS_02X_02X_02X_02X 213
#define IDS_STRING_INTERCOMS_CONNECTED_D_D 214
#define IDS_STRING_OPERATOR_CONSOLE_LOGON_ID 215
#define IDS_STRING_GROUP_INTERCOMS_IN_GROUP 216
#define IDS_STRING_GROUP_STATUS         217
#define IDS_STRING_STATUS_RINGING       218
#define IDS_STRING_STATUS_ONHOOK        219
#define IDC_LIST_DEBUG                  1000
#define IDC_LIST_ICOMS                  1001
#define IDC_BUTTON_TALK                 1002
#define IDC_BUTTON_LISTEN               1003
#define IDC_BUTTON_CHIME                1004
#define IDC_BUTTON_PLAY_FILE            1005
#define IDC_RADIO_SELECTED              1006
#define IDC_RADIO_GROUP                 1007
#define IDC_RADIO_ALL_ACTIVE            1008
#define IDC_RADIO_AUTOMATIC             1009
#define IDC_RADIO_MANUAL                1010
#define IDC_GROUP_LISTEN_MODE           1011
#define IDC_GROUP_TALK_MODE             1012
#define IDC_SPIN_PING_INTERVAL          1013
#define IDC_BUTTON_FDX_START            1013
#define IDC_EDIT_PING_INTERVAL          1014
#define IDC_BUTTON_FDX_MUTE             1014
#define IDC_COMBO_STARTUP_TYPE          1015
#define IDC_BUTTON_NO_LISTEN            1015
#define IDC_COMBO_STARTUP_LANGUAGE      1016
#define IDC_CHECK_BEEPS                 1017
#define IDC_CHECK_HIDE                  1018
#define IDC_CHECK_PTT                   1019
#define IDC_CHECK_CALL_ANNOUNCE         1020
#define IDC_COMBO_ANNOUNCEMENT_AUDIBLE_SOUND 1023
#define IDC_CHECK_RECORD_CALL_WAITING   1024
#define IDC_CHECK_VISUAL_NOTIFICATION   1025
#define IDC_CHECK_AUDIBLE_NOTIFICATION  1026
#define IDC_LIST_CALLS_WAITING          1027
#define IDC_BUTTON_PLAY_PAUSE           1028
#define IDC_BUTTON_STOP                 1029
#define IDC_BUTTON_MUTE                 1030
#define IDC_SLIDER_CQ_PLAYER            1032
#define IDC_GROUP_PLAYER                1033
#define IDC_EDIT_LOGIN_NAME             1034
#define IDC_EDIT_LOGIN_PASSWORD         1035
#define IDC_EDIT_LOGON_IP_ADDRESS       1036
#define IDC_EDIT_LOGON_PORT             1037
#define IDC_BUTTON_LOGON_OPTIONS        1038
#define IDC_BUTTON_HOLD                 1039
#define IDC_BUTTON2                     1040
#define IDC_BUTTON_END                  1040
#define IDC_STATIC_ABOUT_VERSION        1041
#define IDC_STATIC_ABOUT_PICTURE        1042
#define IDC_LIST1                       1043
#define IDC_LIST_ABOUT_COMPONENTS       1043
#define IDC_LIST_GROUPS                 1043
#define IDC_COMBO_WAVE_OUTPUT_DEVICE    1044
#define IDC_LIST_MESSAGES               1044
#define IDC_COMBO_WAVE_OUTPUT_DEVICE2   1045
#define IDC_COMBO_WAVE_INPUT_DEVICE     1045
#define IDC_TAB_PREFERENCES             1046
#define IDC_STATIC_PREFERENCES_PING_GROUP 1047
#define IDC_STATIC_PREF_STARTUP_AUDIO   1048
#define IDC_STATIC_PREF_CALL_ANNOUNCE_GROUP 1049
#define IDC_STATIC_PREF_WAVE_OUT_GROUP  1050
#define IDC_STATIC_PREF_WAVE_IN_GROUP   1051
#define IDC_STATIC_PREF_PING_SECS       1052
#define IDC_STATIC_PREF_ANNOUNCE_RULES_GROUP 1053
#define IDC_STATIC_PREF_QUEUE_AGE       1054
#define IDC_STATIC_PREF_QUEUE_SIZE      1055
#define IDC_EDIT_PREF_QUEUE_AGE         1056
#define IDC_EDIT_PREF_QUEUE_SIZE        1057
#define IDC_COMBO1                      1058
#define IDC_COMBO_PREF_QUEUE_AGE_TYPE   1058
#define IDC_STATIC_PREF_ENTRIES         1059
#define IDC_STATIC_LOGO                 1060
#define IDC_STATIC_VU_METER_SPEAKER     1061
#define IDC_STATIC_VU_METER_MICROPHONE  1062
#define IDC_BUTTON1                     1063
#define IDC_BUTTON_TEST                 1063
#define IDC_BUTTON_GET_VOLUME           1063
#define IDC_BUTTON_BROWSE_TEST_VOLUME_FILE 1063
#define IDC_BUTTON_SEND_TEXT            1063
#define IDC_STATIC_SERVER_INTERCOMS     1064
#define IDC_STATIC_CONSOLE_INTERCOMS    1065
#define IDC_STATIC_STATUS_CONNECTED     1066
#define IDC_STATIC_STATUS_PTT           1067
#define IDC_BUTTON4                     1069
#define IDC_BUTTON_TEST_VOLUME          1069
#define IDC_CHECK1                      1071
#define IDC_CHECK_MICROPHONE_ULAW       1071
#define IDC_CHECK_TEST                  1071
#define IDC_CHECK_SAVE_LOGON            1071
#define IDC_STATIC_CODEC                1072
#define IDC_CHECK2                      1075
#define IDC_CHECK_PLAY_AGAIN            1075
#define IDC_SLIDER1                     1076
#define IDC_SLIDER_MAX_MSEC             1076
#define IDC_STATIC_MAX_MSEC             1077
#define IDC_CHECK_SHOW_DEBUG            1078
#define IDC_STATIC_MIN_MSEC_TEXT        1079
#define IDC_CHECK_SETUP_VOLUME          1080
#define IDC_PROGRESS_SETUP_VOLUME       1082
#define IDC_SLIDER_SETUP_VOLUME         1083
#define IDC_BUTTON_SET_VOLUME           1084
#define IDC_EDIT_TEST_VOLUME_FILE       1085
#define IDC_STATIC_TEST_VOLUME_FILE     1086
#define IDC_CHECK_FORCE_HDX             1087
#define IDC_BUTTON_TEST_AUDIO           1088
#define IDC_TAB_MAIN                    1089
#define IDC_EDIT_TEXT_MESSAGE           1090
#define IDC_CHECK3                      1091
#define IDC_CHECK_VAD                   1091
#define IDC_BUTTON_SESSION_START        1092
#define IDC_BUTTON_SESSION_END          1093
#define IDC_EDIT_TEST_LOGON_NAME        1094
#define IDC_EDIT_TEST_LOGON_PASSWORD    1095
#define IDC_CAMERA                      1095
#define IDC_DELETEME                    1096
#define IDC_BUTTON5                     1097
#define ID_FILE_EXIT                    32771
#define ID_FILE_CAPTUREARCHIVEAUDIO     32772
#define ID_FILE_PLAYAUDIOARCHIVES       32773
#define ID_VIEW_EVENTLOG                32774
#define ID_VIEW_SCREENPOSITION          32775
#define ID_SCREENPOSITION_SAVECURRENTVIEW 32776
#define ID_SCREENPOSITION_RESETTODEFAULT 32777
#define ID_VIEW_PREFERENCES             32778
#define ID_TOOLS_RECORDPROGRAMEVENTSTOFILE 32779
#define ID_TOOLS_CONFIGUREINTERCOMS     32780
#define ID_TOOLS_RESETALLCONNECTIONS    32781
#define ID_TOOLS_II3INTERCOMOSUPDATE    32782
#define ID_CONSOLE_FORWARDINTERCOMS     32783
#define ID_CONSOLE_RETRIEVEINTERCOMS    32784
#define ID_CONSOLE_UNATTENDEDCONSOLE    32785
#define ID_HELP_HELPONUSINGTALKMASTER   32786
#define ID_HELP_ONLINEDOCUMENTATION     32787
#define ID_HELP_DIGITALACOUSTICSWEBSITE 32788
#define ID_HELP_CHECKFORNEWVERSIONSONLINE 32789
#define ID_HELP_ABOUT                   32790
#define ID_VIEW_DEBUGINFORMATION        32791
#define ID_INVISIBLE_INTERCOMNAME       32794
#define ID_INVISIBLE_INTERCOMID         32795
#define ID_INVISIBLE_OSVERSION          32796
#define ID_INVISIBLE_NICVERSION         32797
#define ID_FILE_LOGOFF                  32799
#define ID_TOOLS_OPENSUPPORTFOLDER      32800
#define ID_INVISIBLE_OPTIONS            32801
#define ID_INVISIBLE_RESETINTERCOMCONNECTION 32802
#define ID_TOOLS_SENDTEXTMESSAGE        32803
#define ID_INVISIBLEGROUPMENU_INTERCOMSINGROUP 32804
#define ID_TOOLS_TESTCONSOLEDLL         32805

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
